import type { Metadata } from "next";
import "./globals.css";
import { tree } from "next/dist/build/templates/app-page";


export const metadata: Metadata = {
  title: "HyperX.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
