import type { Metadata } from "next";
import "./globals.css";
import {Provider} from "react-redux"
import { store } from "@/redux/store/store";
import StoreProvider from "./reduxProvider";


export const metadata: Metadata = {
  title: "HyperX.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body suppressHydrationWarning={true}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
